-- 1. Tạo bảng baigiang
CREATE TABLE public.baigiang (
  mabaigiang BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  magv VARCHAR(50) NOT NULL REFERENCES public.giangvien(magv) ON DELETE CASCADE,
  mamon VARCHAR(50) NOT NULL REFERENCES public.monhoc(mamon) ON DELETE CASCADE,
  tieude TEXT NOT NULL,
  mota TEXT,
  loai_file VARCHAR(20) NOT NULL, -- 'video' hoặc 'image' hoặc 'document'
  file_url TEXT NOT NULL,
  dungluong INT, -- bytes
  thoigiantao TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tạo Storage Bucket tên "lectures" (nếu chưa có)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('lectures', 'lectures', true)
ON CONFLICT (id) DO NOTHING;

-- 3. Cho phép đọc file từ Bucket "lectures" cho tất cả mọi người
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING ( bucket_id = 'lectures' );

-- 4. Cho phép upload file vào Bucket "lectures" (Bỏ qua RLS phức tạp để tiện upload trong môi trường Next.js API/Client authenticated)
CREATE POLICY "Allow Uploads" 
ON storage.objects FOR INSERT 
WITH CHECK ( bucket_id = 'lectures' );

-- 5. Cho phép cập nhật/xóa file trong Bucket "lectures"
CREATE POLICY "Allow Updates" 
ON storage.objects FOR UPDATE 
USING ( bucket_id = 'lectures' );

CREATE POLICY "Allow Deletes" 
ON storage.objects FOR DELETE 
USING ( bucket_id = 'lectures' );
